name: sail-xprecip-dev
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python
  - arm_pyart
  - matplotlib
  - hvplot
  - jupyterlab
  - holoviews
  - geoviews
  - cartopy
  - numpy
  - dask
  - dask-labextension
  - distributed
  - xarray
  - pandas
  - datashader
  - geopandas
  - fiona
  - pip
  - pip:
    - -r doc-requirements.txt
